Qa 577 add CI section
zciluk/automation-roadmap pull request #17
Opened 2021-11-30 10:35 UTC by galeza

2021-11-30 11:57 UTC, woytekn requested changes

2021-11-30 11:57 UTC, woytekn commented on src/data/roadmapData.json
> +              "description": "Describes Continues Integration. The artcle contains several links to the useful resources.",
"Continues" - typo

2021-11-30 11:57 UTC, woytekn commented on src/data/roadmapData.json
> +              "urlLabel": "Basic knowledge about Continues Integration"
"Continues" - typo

2021-11-30 11:57 UTC, woytekn commented on src/data/roadmapData.json
> +              "description": "Presents types of tests and CI. Describes how to adopt Continues Integration",
"Continues" - typo

2021-11-30 12:38 UTC, galeza commented on src/data/roadmapData.json
> +              "description": "Describes Continues Integration. The artcle contains several links to the useful resources.",
Ok, fixed

2021-11-30 12:38 UTC, galeza commented on src/data/roadmapData.json
> +              "urlLabel": "Basic knowledge about Continues Integration"
Ok, fixed

2021-11-30 12:38 UTC, galeza commented on src/data/roadmapData.json
> +              "description": "Presents types of tests and CI. Describes how to adopt Continues Integration",
Ok, fixed

2021-12-01 14:11 UTC, zciluk requested changes
Very nice links, only some minor changes requested.

2021-12-01 14:11 UTC, zciluk commented on src/data/roadmapData.json
> +              "description": "Continuous Integration with Jenkins",
I would add some more description here to distinct it more from the first link provided. Like "It's a video course that teaches A B and C"

2021-12-01 14:11 UTC, zciluk commented on src/data/roadmapData.json
> +              "description": "Learn how to run Cypress on a generic CI, on GitHub Actions, on CircleCI, and on Netlify. You need a free acount.",
It would be nice to include here Parts in description - Part 1 and Part 2 to clearly distinct them

2021-12-02 12:45 UTC, zciluk approved these changes
LGTM

2021-12-06 10:24 UTC, woytekn approved these changes

2021-12-06 10:26 UTC, merged